daily 2023-04-12

diff --git a/bin/sh/gpp b/bin/sh/gpp
--- a/bin/sh/gpp
+++ b/bin/sh/gpp
@@ -16,21 +16,24 @@ function addChanges() {
     local CHANGES="$(git status --porcelain)"
     local CHANGES_NUM="$(echo -n $CHANGES | grep -c '^')"
     # if [[ `git status --porcelain` ]]; then  # have changes
-    if [[ "$CHANGES_NUM" -gt 0 ]]; then  # have changes
+    if [[ "$CHANGES_NUM" -gt 0 ]]; then # have changes
         echo -e "\n${N_GREEN}==> Add All Changes${NC}"
         echo "$CHANGES"
         git add -A
 
         echo -e "\n${N_GREEN}==> Commit${NC}"
         git commit -m "daily $(date "+%Y-%m-%d")"
-    else   # No changes
+    else # No changes
 
     fi
 }
 
 function fetch() {
     echo -e "\n${N_GREEN}==> Fetch${NC}"
-    git fetch --all --prune || (echo -e "${N_RED}Can't Fetch!!!${NC}"; exit 1)
+    git fetch --all --prune || (
+        echo -e "${N_RED}Can't Fetch!!!${NC}"
+        exit 1
+    )
 }
 
 function rebase() {
@@ -40,18 +43,26 @@ function rebase() {
 
     if git branch -a --contains "${remoteBranch}" &>/dev/null; then # 有远程分支
         echo -e "\n${N_GREEN}==> Pull Rebase${NC}"
-        git rebase "${remoteBranch}" || (echo -e "${N_RED}Can't Rebase!!!${NC}"; exit 1)
+        git rebase "${remoteBranch}" || (
+            echo -e "${N_RED}Can't Rebase!!!${NC}"
+            exit 1
+        )
     fi
 }
 
 function push() {
     echo -e "\n${N_GREEN}==> Push${NC}"
     if git branch -a --contains "${remoteBranch}" &>/dev/null; then # 有远程分支
-        git push || (echo -e "${N_RED}Can't Push!!! ${NC}"; exit 1)
+        git push || (
+            echo -e "${N_RED}Can't Push!!! ${NC}"
+            exit 1
+        )
     else
-        git push -u origin HEAD || (echo -e "${N_RED}Can't Push!!! ${NC}"; exit 1)
+        git push -u origin HEAD || (
+            echo -e "${N_RED}Can't Push!!! ${NC}"
+            exit 1
+        )
     fi
 }
 
 addChanges && fetch && rebase && push
-
